name: Unit tests, linting, and formatting
on: [push]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: |
          rustup override set stable
          rustup update stable
          cargo install cargo-nextest
      - name: Run tests
        run: cargo nextest run
      - name: Lint
        run: cargo clippy
      - name: Check formatting
        run: cargo fmt --check
